# Generated by Django 3.2.7 on 2021-09-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1024, verbose_name='问题')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='名字')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ号')),
                ('score', models.IntegerField(default=0, max_length=16, verbose_name='分数')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.CharField(max_length=1024, verbose_name='选项')),
                ('is_true', models.BooleanField(verbose_name='正确还是错误选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
    ]
