# Generated by Django 3.2.7 on 2021-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
    ]
