# Generated by Django 3.2.7 on 2021-09-07 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_options', to='game.question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1024, unique=True, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=128, unique=True, verbose_name='QQ号'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='game.options', verbose_name='选择答案')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_questions', to='game.question', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '用户回答结果',
                'verbose_name_plural': '用户回答结果',
            },
        ),
    ]
