# Generated by Django 3.2.7 on 2021-09-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210907_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '玩家回答结果', 'verbose_name_plural': '玩家回答结果'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': '问题选项', 'verbose_name_plural': '问题选项'},
        ),
        migrations.AddField(
            model_name='user',
            name='answer_record',
            field=models.TextField(default='-', verbose_name='答题记录'),
        ),
        migrations.AddField(
            model_name='user',
            name='answer_time',
            field=models.CharField(default='2021-09-08 14:27:00', max_length=128, verbose_name='答题时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='答题分数'),
        ),
    ]
