# Generated by Django 3.2.7 on 2021-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210908_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer_time',
            field=models.CharField(default='2021-09-08 14:40:47', max_length=128, verbose_name='答题时间'),
        ),
    ]
