# Generated by Django 3.2.7 on 2021-09-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210908_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='game.options', verbose_name='选择答案'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_questions', to='game.question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer_time',
            field=models.CharField(default='2021-09-08 14:46:18', max_length=128, verbose_name='答题时间'),
        ),
    ]
