# Generated by Django 3.2.7 on 2021-09-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210908_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_time',
            field=models.CharField(default='2021-09-08 15:04:58', max_length=128, verbose_name='答题时间'),
        ),
    ]
