# Generated by Django 3.2.7 on 2021-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_user_answer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer_time',
            field=models.CharField(default='2021-09-08 15:05:06', max_length=128, verbose_name='答题时间'),
        ),
    ]
